# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Any, Dict

from .async_base_client import AsyncBaseClient
from .create_youtube_channel import CreateYoutubeChannel


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def create_youtube_channel(
        self, remote_youtube_channel_id: str, **kwargs: Any
    ) -> CreateYoutubeChannel:
        query = gql(
            """
            mutation CreateYoutubeChannel($remote_youtube_channel_id: String!) {
              insert_youtube_channels_one(
                object: {remote_youtube_channel_id: $remote_youtube_channel_id}
              ) {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "remote_youtube_channel_id": remote_youtube_channel_id
        }
        response = await self.execute(
            query=query,
            operation_name="CreateYoutubeChannel",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CreateYoutubeChannel.model_validate(data)
