# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateYoutubeVideoObject(BaseModel):
    insert_youtube_video_objects_one: Optional[
        "CreateYoutubeVideoObjectInsertYoutubeVideoObjectsOne"
    ]


class CreateYoutubeVideoObjectInsertYoutubeVideoObjectsOne(BaseModel):
    id: Any


CreateYoutubeVideoObject.model_rebuild()
