# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Optional

from .base_model import BaseModel


class CreateYoutubeChannelDetails(BaseModel):
    insert_youtube_channels: Optional[
        "CreateYoutubeChannelDetailsInsertYoutubeChannels"
    ]


class CreateYoutubeChannelDetailsInsertYoutubeChannels(BaseModel):
    affected_rows: int


CreateYoutubeChannelDetails.model_rebuild()
