# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Optional

from .base_model import BaseModel


class CreateYoutubeVideoDetails(BaseModel):
    insert_youtube_video_details: Optional[
        "CreateYoutubeVideoDetailsInsertYoutubeVideoDetails"
    ]


class CreateYoutubeVideoDetailsInsertYoutubeVideoDetails(BaseModel):
    affected_rows: int


CreateYoutubeVideoDetails.model_rebuild()
