# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateYoutubeChannel(BaseModel):
    insert_youtube_channels_one: Optional[
        "CreateYoutubeChannelInsertYoutubeChannelsOne"
    ]


class CreateYoutubeChannelInsertYoutubeChannelsOne(BaseModel):
    id: Any


CreateYoutubeChannel.model_rebuild()
