# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Optional

from .base_model import BaseModel


class CreateYoutubeVideos(BaseModel):
    insert_youtube_videos: Optional["CreateYoutubeVideosInsertYoutubeVideos"]


class CreateYoutubeVideosInsertYoutubeVideos(BaseModel):
    affected_rows: int


CreateYoutubeVideos.model_rebuild()
