# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateYoutubeChannelThumbnailObject(BaseModel):
    insert_youtube_channel_thumbnail_objects_one: Optional[
        "CreateYoutubeChannelThumbnailObjectInsertYoutubeChannelThumbnailObjectsOne"
    ]


class CreateYoutubeChannelThumbnailObjectInsertYoutubeChannelThumbnailObjectsOne(
    BaseModel
):
    id: Any


CreateYoutubeChannelThumbnailObject.model_rebuild()
