# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Any, Optional

from .base_model import BaseModel


class CreateYoutubeVideoThumbnailObject(BaseModel):
    insert_youtube_video_thumbnail_objects_one: Optional[
        "CreateYoutubeVideoThumbnailObjectInsertYoutubeVideoThumbnailObjectsOne"
    ]


class CreateYoutubeVideoThumbnailObjectInsertYoutubeVideoThumbnailObjectsOne(BaseModel):
    id: Any


CreateYoutubeVideoThumbnailObject.model_rebuild()
