# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class cursor_ordering(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class order_by(str, Enum):
    asc = "asc"
    asc_nulls_first = "asc_nulls_first"
    asc_nulls_last = "asc_nulls_last"
    desc = "desc"
    desc_nulls_first = "desc_nulls_first"
    desc_nulls_last = "desc_nulls_last"


class youtube_channel_details_select_column(str, Enum):
    created_at = "created_at"
    custom_url = "custom_url"
    description = "description"
    fetched_at = "fetched_at"
    id = "id"
    privacy_status = "privacy_status"
    published_at = "published_at"
    title = "title"
    updated_at = "updated_at"
    youtube_channel_id = "youtube_channel_id"


class youtube_channel_thumbnail_objects_select_column(str, Enum):
    content_type = "content_type"
    created_at = "created_at"
    fetched_at = "fetched_at"
    id = "id"
    object_key = "object_key"
    object_size = "object_size"
    sha256_digest = "sha256_digest"
    updated_at = "updated_at"
    youtube_channel_thumbnail_id = "youtube_channel_thumbnail_id"


class youtube_channel_thumbnails_select_column(str, Enum):
    created_at = "created_at"
    fetched_at = "fetched_at"
    height = "height"
    id = "id"
    key = "key"
    updated_at = "updated_at"
    url = "url"
    width = "width"
    youtube_channel_id = "youtube_channel_id"


class youtube_channels_constraint(str, Enum):
    youtube_channels_pkey = "youtube_channels_pkey"
    youtube_channels_remote_youtube_channel_id_key = (
        "youtube_channels_remote_youtube_channel_id_key"
    )


class youtube_channels_select_column(str, Enum):
    created_at = "created_at"
    enabled = "enabled"
    id = "id"
    last_fetched_at = "last_fetched_at"
    registered_at = "registered_at"
    remote_youtube_channel_id = "remote_youtube_channel_id"
    updated_at = "updated_at"


class youtube_channels_update_column(str, Enum):
    enabled = "enabled"
    last_fetched_at = "last_fetched_at"
    registered_at = "registered_at"
