# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import List, Optional

from .base_model import BaseModel


class GetDownloadableYoutubeVideoThumbnails(BaseModel):
    youtube_video_thumbnails: List[
        "GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails"
    ]


class GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails(BaseModel):
    url: Optional[str]
    key: Optional[str]
    width: Optional[int]
    height: Optional[int]
    youtube_video: Optional[
        "GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnailsYoutubeVideo"
    ]


class GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnailsYoutubeVideo(
    BaseModel
):
    remote_youtube_video_id: str


GetDownloadableYoutubeVideoThumbnails.model_rebuild()
GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails.model_rebuild()
