# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import List

from .base_model import BaseModel


class GetDownloadableYoutubeVideos(BaseModel):
    youtube_videos: List["GetDownloadableYoutubeVideosYoutubeVideos"]


class GetDownloadableYoutubeVideosYoutubeVideos(BaseModel):
    remote_youtube_video_id: str


GetDownloadableYoutubeVideos.model_rebuild()
