# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import List

from .base_model import BaseModel


class GetUpdatableYoutubeChannels(BaseModel):
    youtube_channels: List["GetUpdatableYoutubeChannelsYoutubeChannels"]


class GetUpdatableYoutubeChannelsYoutubeChannels(BaseModel):
    remote_youtube_channel_id: str


GetUpdatableYoutubeChannels.model_rebuild()
