# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import List

from .base_model import BaseModel


class GetDownloadableYoutubeVideoThumbnails(BaseModel):
    youtube_video_thumbnails: List[
        "GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails"
    ]


class GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails(BaseModel):
    url: str
    key: str
    width: int
    height: int
    youtube_video: (
        "GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnailsYoutubeVideo"
    )


class GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnailsYoutubeVideo(
    BaseModel
):
    remote_youtube_video_id: str


GetDownloadableYoutubeVideoThumbnails.model_rebuild()
GetDownloadableYoutubeVideoThumbnailsYoutubeVideoThumbnails.model_rebuild()
