# Generated by ariadne-codegen
# Source: graphql_queries/

from typing import Optional

from .base_model import BaseModel


class UpsertYoutubeVideos(BaseModel):
    insert_youtube_videos: Optional["UpsertYoutubeVideosInsertYoutubeVideos"]


class UpsertYoutubeVideosInsertYoutubeVideos(BaseModel):
    affected_rows: int


UpsertYoutubeVideos.model_rebuild()
